---
openapi: 3.0.0
info:
  title: Edifice - Auth - API ðŸš§ðŸš§
  description: This part represant the documentation of the Edifice api use in auth module
  version: 4.10.0
servers:
  - url: /
tags:
  - name: oauth2
    description: Authenticate using OAuth 2.0
    externalDocs:
      description: For more information
      url: "https://oauth.net/2/grant-types/authorization-code/"
  - name: cas
    description: ðŸš§ //TODO
  - name: auth
    description: ðŸš§ //TODO
  - name: cgu
    description: ðŸš§ //TODO
  - name: openid
    description: ðŸš§ //TODO
  - name: saml
    description: ðŸš§ //TODO
paths:
  /auth/oauth2/auth:
    get:
      tags:
        - oauth2
      summary: Authenticate using OAuth 2.0 with Authorization Code
      parameters:
        - name: response_type
          in: query
          description: Add description
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: client_id
          in: query
          description: Add description
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: redirect_uri
          in: query
          description: Add description
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: scope
          in: query
          description: Add description
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: state
          in: query
          description: Add description
          required: false
          style: form
          explode: true
          schema:
            type: string
        - name: nonce
          in: query
          description: Add description
          required: false
          style: form
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response, redirection url with code=&state=
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/oauth2/token:
    get:
      tags:
        - oauth2
      summary: Obtain OAuth2 Token
      description: |
        Endpoint to obtain an OAuth2 token using the password grant type.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  example: password
                username:
                  type: string
                  example: "{USERNAME}"
                password:
                  type: string
                  example: "{PASSWORD}"
                scope:
                  type: string
                  example: "{SCOPE}"
                client_id:
                  type: string
                  example: "{CLIENT_ID}"
                client_secret:
                  type: string
                  example: "{CLIENT_SECRET}"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  token_type:
                    type: string
                    example: Bearer
                  access_token:
                    type: string
                    example: "1413b31c-b240-453a-bc1e-3773cd31adc9"
                  refresh_token:
                    type: string
                    example: "9e746d64-3fa8-4ff8-88b3-2d8314f56179"
                  expires_in:
                    type: integer
                    example: 3600
                  scope:
                    type: string
                    example: "{SCOPE}"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: invalid_request
                  error_description:
                    type: string
                    example: "Invalid request parameters"
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
    post:
      tags:
        - oauth2
      summary: Get OAuth Token
      parameters:
        - name: grant_type
          in: query
          description: The type of grant being used
          required: true
          schema:
            type: string
        - name: code
          in: query
          description: The authorization code received from the authorization server
          required: true
          schema:
            type: string
        - name: redirect_uri
          in: query
          description: The redirect URI used in the authorization request
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  token_type:
                    type: string
                    example: Bearer
                  access_token:
                    type: string
                    example: 37995391-3976-4811-a72a-0cd55522e1f6
                  refresh_token:
                    type: string
                    example: ce472190-0fea-4826-a0d5-c22e8082b49d
                  expires_in:
                    type: integer
                    example: 3600
                  scope:
                    type: string
                    example: userinfo
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: invalid_request
                  error_description:
                    type: string
                    example: "redirect_uri not found"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: invalid_grant
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/context:
    get:
      tags:
        - auth
      summary: Get authentication context
      parameters:
        - name: X-Forwarded-Host
          in: header
          description: The original host requested by the client in the "Host" HTTP request header field.
          required: false
          schema:
            type: string
        - name: Host
          in: header
          description: The domain name of the server (for virtual hosting), and the TCP port number on which the server is listening.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                callBack: ""
                cgu: true
                passwordRegex: ".*"
                mandatory: {}
                passwordRegexI18n:
                  fr: "Choisissez 8 caractÃ¨res minimum, lettres et chiffres obligatoires."
                  en: "password.errors"
                mfaConfig: []
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/user/requirements:
    get:
      tags:
        - auth
      summary: Get user requirements
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                forceChangePassword: false
                needRevalidateTerms: false
                needRevalidateEmail: false
                needRevalidateMobile: false
                needMfa: false
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/oauth2/userinfo:
    get:
      tags:
        - oauth2
      summary: Get User Information
      parameters:
        - name: Authorization
          in: header
          description: The access token obtained from the OAuth token endpoint
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                level: ""
                login: severine.alexandre
                lastName: ALEXANDRE
                firstName: SEVERINE
                externalId: "5555959"
                username: SEVERINE ALEXANDRE
                type: ENSEIGNANT
                childrenIds: []
                uai:
                  - "0805432C"
                userId: 2bacdfd2-b59c-4b21-a23e-f6346e02fc4a
                classId: "55567$3ARMS"
                schoolName: CollÃ¨ge Denis Poisson
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - BearerAuth: []
        - oAuth2AuthCode:
            - userinfo
            - conversation
    post:
      tags:
        - oauth2
      summary: Return The User Information
      parameters:
        - name: Authorization
          in: header
          description: The access token obtained from the OAuth token endpoint
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                level: ""
                login: severine.alexandre
                lastName: ALEXANDRE
                firstName: SEVERINE
                externalId: "5555959"
                username: SEVERINE ALEXANDRE
                type: ENSEIGNANT
                childrenIds: []
                uai:
                  - "0805432C"
                userId: 2bacdfd2-b59c-4b21-a23e-f6346e02fc4a
                classId: "55567$3ARMS"
                schoolName: CollÃ¨ge Denis Poisson
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - BearerAuth: []
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/internal/userinfo:
    get:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/activation/match:
    post:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/rest/match:
    post:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/activation/no-login:
    post:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/forgot-id:
    post:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/password-channels:
    get:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/forgot-password:
    post:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/sendResetPassword:
    post:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/generatePasswordRenewalCode:
    post:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/massGeneratePasswordRenewalCode:
    post:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/block/{userId}:
    put:
      tags:
        - auth
      summary: ðŸš§ //TODO
      parameters:
        - name: userId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/block:
    put:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/reset:
    post:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/cgu/revalidate:
    get:
      tags:
        - cgu
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/user/mfa/code:
    get:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
    post:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/session:
    delete:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/generate/otp:
    post:
      tags:
        - auth
      summary: Generate One-Time Password (OTP)
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                otp: "3dsfsds4"
                otpiat: 313213Ã©
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/configure/welcome:
    get:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
    put:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/openid/certs:
    get:
      tags:
        - openid
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/openid/login:
    get:
      tags:
        - openid
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/openid/authenticate:
    get:
      tags:
        - openid
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/openid/mapingUser:
    post:
      tags:
        - openid
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/openid/slo:
    get:
      tags:
        - openid
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/openid/webhook:
    post:
      tags:
        - openid
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/redirect:
    get:
      tags:
        - auth
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/saml/wayf:
    get:
      tags:
        - saml
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/saml/authn/{providerId}:
    get:
      tags:
        - saml
      summary: ðŸš§ //TODO
      parameters:
        - name: providerId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/saml/sso/{providerId}:
    get:
      tags:
        - saml
      summary: ðŸš§ //TODO
      parameters:
        - name: providerId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/saml/redirect/sso:
    get:
      tags:
        - saml
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/saml/post/sso:
    post:
      tags:
        - saml
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/saml/metadata:
    get:
      tags:
        - saml
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/saml/acs:
    post:
      tags:
        - saml
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/saml/slo:
    get:
      tags:
        - saml
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/saml/selectUser:
    get:
      tags:
        - saml
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation
  /auth/test/newdevicemail:
    get:
      tags:
        - saml
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /cas/configuration/reload:
    get:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /cas/configuration/mappings/reload:
    get:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

  /cas/configuration/mappings:
    post:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation


  /cas/configuration/mappings/:mappingId:
    delete:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation


  /cas/configuration/mappings/:mappingId/usage:
    get:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation


  /cas/configuration/mappings/:mappingId/usage/:structureId:
    get:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation


  /cas/configuration/simulate:
    get:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation


  /cas/login:
    get:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation


  /cas/oauth/login:
    get:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation


  /cas/samlValidate:
    get:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation


  /cas/serviceValidate:
    get:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation


  /cas/proxyValidate:
    get:
      tags:
        - cas
      summary: ðŸš§ //TODO
      responses:
        "200":
          description: Successful response
        "404":
          description: Bad request
        "302":
          description: Authentication failed. HTTP Client is redirected to $SERVER_DOMAIN/auth/login?callback=$SERVER_DOMAIN/
      security:
        - oAuth2AuthCode:
            - userinfo
            - conversation

components:
  schemas:
    Error:
      required:
        - message
      type: object
      properties:
        message:
          type: string
          description: A human-readable error message
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      description: "For more information, see https://opendigitaleducation.atlassian.net/wiki/spaces/PUBLIC/pages/1184891013/Connecteur+-+SSO+oAuth2"
      flows:
        authorizationCode:
          authorizationUrl: /auth/oauth2/auth
          tokenUrl: /auth/oauth2/token
          scopes:
            userinfo: Get user's identification information
            conversation: Access to conversation API
    BearerAuth:
      type: http
      scheme: bearer
